# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04


# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - method: pip
      path: package