# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8

before_install:
  - pip install -U pip cython
  - pip install --no-build-isolation hypothesis packaging pytest pytest-cov pytest-xdist codecov
install:
  - pip install -r requirements.txt
  - python setup.py install && (cd tests/ && python setup.py install)
script:
  - python -m pytest tests/ENPMDATests --disable-pytest-warnings --cov=ENPMDA -rsx
after_success:
  - bash <(curl -s https://codecov.io/bash)
